# NOTE: it is assumed all data in a single file has the same DSID 
path_to_rootfiles: 
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364700.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364701.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364702.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364703.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364704.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364705.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'
  - '/share/data1/yzhu/jetm2/user.yuanda.mc20_13TeV.364706.e7142_s3681_r13144_r13146_p7053.with_parT_ANALYSIS.root/*.root'

n_files: null

# Using the new fractional batching system
event_fractions: {0.5: 1} # 50% of the data
event_fraction_idx: null

# Output directory for your user space
out_dir: "/home/xzcqsfhu/lundtoptagger/qg_analysis_data/jet2m_ParT/data_160_1300GeV_3.2_4.5_eta"
out_file_name_graphs: "graphs_{id}{frac}_ln_kT_cut_{kT_cut}{include_pt}"
out_file_name_root: "data_{id}{frac}_ln_kT_cut_{kT_cut}.root"

id: "dijet_ParT"

# -------------------------------------------------------------------
# Use SRJ signal config
# -------------------------------------------------------------------
signal_config_file: "configs/config_signal_srj.yaml" # Use lowercase as in Yuanda's repo
signal: srj              
signal_name_in_weight: False   

# -------------------------------------------------------------------
# selection and output variables
# -------------------------------------------------------------------
kT_cut: null
include_pt: True